export const full_list_html = `<div>
                  <li class="poster-container" data-owner-rating="0">
                    <div class="react-component poster film-poster film-poster-352504 linked-film-poster" data-component-class="globals.comps.FilmPosterComponent" data-film-id="352504" data-item-id="film:352504" data-film-name="Esteros" data-film-slug="esteros" data-poster-url="/film/esteros/image-150/" data-new-list-with-film-action="/list/new/with/esteros/" data-remove-from-watchlist-action="/film/esteros/remove-from-watchlist/" data-add-to-watchlist-action="/film/esteros/add-to-watchlist/" data-rate-action="/s/film:352504/rate/" data-film-link="/film/esteros/"><div><img src="https://a.ltrbxd.com/resized/film-poster/3/5/2/5/0/4/352504-esteros-0-125-0-187-crop.jpg?v=fe9b46b1c4" width="125" height="187" alt="Esteros" srcset="https://a.ltrbxd.com/resized/film-poster/3/5/2/5/0/4/352504-esteros-0-250-0-375-crop.jpg?v=fe9b46b1c4 2x" class="image"><a href="/film/esteros/" class="frame" data-original-title="Esteros (2016)"><span class="frame-title">Esteros (2016)</span><span class="overlay"></span></a></div></div>
                    </li>
                    <li class="poster-container" data-owner-rating="0">
                        <div class="react-component poster film-poster film-poster-26616 linked-film-poster" data-component-class="globals.comps.FilmPosterComponent" data-film-id="26616" data-item-id="film:26616" data-film-name="The White Ribbon" data-film-slug="the-white-ribbon" data-poster-url="/film/the-white-ribbon/image-150/" data-new-list-with-film-action="/list/new/with/the-white-ribbon/" data-remove-from-watchlist-action="/film/the-white-ribbon/remove-from-watchlist/" data-add-to-watchlist-action="/film/the-white-ribbon/add-to-watchlist/" data-rate-action="/s/film:26616/rate/" data-film-link="/film/the-white-ribbon/"><div><img src="https://a.ltrbxd.com/resized/film-poster/2/6/6/1/6/26616-the-white-ribbon-0-125-0-187-crop.jpg?v=4f4172dea5" width="125" height="187" alt="The White Ribbon" srcset="https://a.ltrbxd.com/resized/film-poster/2/6/6/1/6/26616-the-white-ribbon-0-250-0-375-crop.jpg?v=4f4172dea5 2x" class="image"><a href="/film/the-white-ribbon/" class="frame" data-original-title="The White Ribbon (2009)"><span class="frame-title">The White Ribbon (2009)</span><span class="overlay"></span></a></div></div>
                    </li>
                    <li class="poster-container" data-owner-rating="0">
                     <div class="react-component poster film-poster film-poster-985816 linked-film-poster" data-component-class="globals.comps.FilmPosterComponent" data-film-id="985816" data-item-id="film:985816" data-film-name="Daisy Jones &amp; the Six" data-film-slug="daisy-jones-the-six" data-poster-url="/film/daisy-jones-the-six/image-150/" data-new-list-with-film-action="/list/new/with/daisy-jones-the-six/" data-remove-from-watchlist-action="/film/daisy-jones-the-six/remove-from-watchlist/" data-add-to-watchlist-action="/film/daisy-jones-the-six/add-to-watchlist/" data-rate-action="/s/film:985816/rate/" data-film-link="/film/daisy-jones-the-six/"><div><img src="https://a.ltrbxd.com/resized/film-poster/9/8/5/8/1/6/985816-daisy-jones-the-six-0-125-0-187-crop.jpg?v=9b445c7209" width="125" height="187" alt="Daisy Jones &amp; the Six" srcset="https://a.ltrbxd.com/resized/film-poster/9/8/5/8/1/6/985816-daisy-jones-the-six-0-250-0-375-crop.jpg?v=9b445c7209 2x" class="image"><a href="/film/daisy-jones-the-six/" class="frame" data-original-title="Daisy Jones &amp; the Six (2023)"><span class="frame-title">Daisy Jones &amp; the Six (2023)</span><span class="overlay"></span></a></div></div>
                     </li>
                     <a class="next" href="/page2"></a>
                 </div>`;

export const list_without_next_html = `<div>
                        <li class="poster-container" data-owner-rating="0">
                          <div class="react-component poster film-poster film-poster-352504 linked-film-poster" data-component-class="globals.comps.FilmPosterComponent" data-film-id="352504" data-item-id="film:352504" data-film-name="Esteros" data-film-slug="esteros" data-poster-url="/film/esteros/image-150/" data-new-list-with-film-action="/list/new/with/esteros/" data-remove-from-watchlist-action="/film/esteros/remove-from-watchlist/" data-add-to-watchlist-action="/film/esteros/add-to-watchlist/" data-rate-action="/s/film:352504/rate/" data-film-link="/film/esteros/"><div><img src="https://a.ltrbxd.com/resized/film-poster/3/5/2/5/0/4/352504-esteros-0-125-0-187-crop.jpg?v=fe9b46b1c4" width="125" height="187" alt="Esteros" srcset="https://a.ltrbxd.com/resized/film-poster/3/5/2/5/0/4/352504-esteros-0-250-0-375-crop.jpg?v=fe9b46b1c4 2x" class="image"><a href="/film/esteros/" class="frame" data-original-title="Esteros (2016)"><span class="frame-title">Esteros (2016)</span><span class="overlay"></span></a></div></div>
                          </li>
                          <li class="poster-container" data-owner-rating="0">
                              <div class="react-component poster film-poster film-poster-26616 linked-film-poster" data-component-class="globals.comps.FilmPosterComponent" data-film-id="26616" data-item-id="film:26616" data-film-name="The White Ribbon" data-film-slug="the-white-ribbon" data-poster-url="/film/the-white-ribbon/image-150/" data-new-list-with-film-action="/list/new/with/the-white-ribbon/" data-remove-from-watchlist-action="/film/the-white-ribbon/remove-from-watchlist/" data-add-to-watchlist-action="/film/the-white-ribbon/add-to-watchlist/" data-rate-action="/s/film:26616/rate/" data-film-link="/film/the-white-ribbon/"><div><img src="https://a.ltrbxd.com/resized/film-poster/2/6/6/1/6/26616-the-white-ribbon-0-125-0-187-crop.jpg?v=4f4172dea5" width="125" height="187" alt="The White Ribbon" srcset="https://a.ltrbxd.com/resized/film-poster/2/6/6/1/6/26616-the-white-ribbon-0-250-0-375-crop.jpg?v=4f4172dea5 2x" class="image"><a href="/film/the-white-ribbon/" class="frame" data-original-title="The White Ribbon (2009)"><span class="frame-title">The White Ribbon (2009)</span><span class="overlay"></span></a></div></div>
                          </li>
                          <li class="poster-container" data-owner-rating="0">
                           <div class="react-component poster film-poster film-poster-985816 linked-film-poster" data-component-class="globals.comps.FilmPosterComponent" data-film-id="985816" data-item-id="film:985816" data-film-name="Daisy Jones &amp; the Six" data-film-slug="daisy-jones-the-six" data-poster-url="/film/daisy-jones-the-six/image-150/" data-new-list-with-film-action="/list/new/with/daisy-jones-the-six/" data-remove-from-watchlist-action="/film/daisy-jones-the-six/remove-from-watchlist/" data-add-to-watchlist-action="/film/daisy-jones-the-six/add-to-watchlist/" data-rate-action="/s/film:985816/rate/" data-film-link="/film/daisy-jones-the-six/"><div><img src="https://a.ltrbxd.com/resized/film-poster/9/8/5/8/1/6/985816-daisy-jones-the-six-0-125-0-187-crop.jpg?v=9b445c7209" width="125" height="187" alt="Daisy Jones &amp; the Six" srcset="https://a.ltrbxd.com/resized/film-poster/9/8/5/8/1/6/985816-daisy-jones-the-six-0-250-0-375-crop.jpg?v=9b445c7209 2x" class="image"><a href="/film/daisy-jones-the-six/" class="frame" data-original-title="Daisy Jones &amp; the Six (2023)"><span class="frame-title">Daisy Jones &amp; the Six (2023)</span><span class="overlay"></span></a></div></div>
                           </li>
                       </div>`;
